# Generated by Django 4.2.2 on 2024-10-20 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_alter_user_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mobile",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Mobile number must be exactly 10 digits",
                        regex="^\\d{10}$",
                    )
                ],
            ),
        ),
    ]
